config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as:'about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

 validates :title, presence: true
 validates :body, presence: true, length: {maximum:200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)

  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
     @books = Book.all
     @user = current_user
     render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user_info = current_user
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] ="You have updated user successfully."
     redirect_to user_path
    else
     render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url:book_path(@book), method: :patch do |f| %>
<div class="form-group">
 <label for="book_title">Title</label>
  <%= f.text_field :title %>
</div>

<div class="form-group">
  <label for="book_opinion">Opinion</p>
  <%= f.text_area :body %>
</div>

 <div class="form-group">
  <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" />
 </div>

<% end %>

<%= link_to "Show", book_path(@book) %>
<a>|</a>
<%= link_to "Back", books_path %>

</div>

app/views/books/index.html.erb
<div class='col-md-3'>
   <%= render 'devise/shared/user_info', user: @user %>
   <%= render 'devise/shared/new_book', book: @book %>
  </div>
<div class='col-md-8 offset-md-1'>
<h2>Books</h2>
<table class='table table-hover table-inverse'>
 <thead>
  <tr>
   <th>Title</th>
   <th>Option</th>
  </tr>
 </thead>
 <tbody>
  <% @books.each do |book| %>
   <tr>
    <td><!--投稿ユーザー画像-->
     <%= link_to user_path(book.user) do %>
      <%= image_tag book.user.get_profile_image(100, 100) %>
     <% end %>
    </td>
    <td>
     <%= link_to book.title, book_path(book) %>
    </td>
    <td>
     <%= book.body %>
    </td>
   </tr>
  <% end %>
 </tbody>
</table>
</div>

app/views/books/new.html.erb
<h2>New book</h2><!--共通部分-->
 <%= form_with model: @book do |f| %>

  <h4>Title</h4>
   <%= f.text_field :title %>

  <h4>Opinion</h4>
   <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>

 <% end %>

app/views/books/show.html.erb
<div class="col-md-3">
  <%= render 'devise/shared/user_info', user: @user %>
  <%= render 'devise/shared/new_book', book: @book_new %>
</div>

<div class='col-md-8 offset-md-1'>
 <h2>Book detail</h2>
 <table class="table">
  <tbody>
    <tr>
      <td>
        <div><%= link_to image_tag(@book.user.get_profile_image(100,100)), user_path(@book.user) %></div>
        <div><%= link_to @book.user.name, user_path(@book.user) %></div>
      </td>
      <td>
        <%= link_to @book.title, book_path(@book) %>
      </td>
      <td>
        <%= @book.body %>
      </td>
      <td>
        <% if @book.user == current_user %>
         <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success edit_book_83203" %>
        <% end %>
      </td>
      <td>
        <% if @book.user == current_user %>
         <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-sm btn-danger destroy_book_83203" %>
        <% end %>
      </td>
    </tr>
  </tbody>
 </table>
</div>

app/views/homes/about.html.erb
 <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
  <h1 class="px-3 mx-auto">
   Welcome to <i class="fas fa-book"></i>
   <strong>Bookers</strong>
   !
  </h1>
 </div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
<h1>
  <strong>Welcome to</strong>
  <i class="fas fa-book"></i>
  <strong>Bookers</strong>
  !!
</h1>
<p>
  in <i class="fas fa-book"></i><strong>bookers</strong>,
</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<P>about various books!</P>
<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
    <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 " %>
  </div>
  <div class="row">
    <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block " %>
  </div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
     <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user), class:"text-light" do %>
        <i class="fas fa-home" ></i>Home
        <% end %>
      </li>
      <li>
        <%= link_to users_path, class:"text-light" do %>
        <i class="fas fa-users"></i>Users
        <% end %>
      </li>
      <li>
        <%= link_to books_path, class:"text-light" do %>
        <i class="fas fa-book-open"></i>Books
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class:"text-light" do %>
        <i class="fas fa-sign-out-alt"></i>Log out
        <% end %>
      </li>
     <% else %>
      <li>
        <%= link_to root_path, class:"text-light" do %>
        <i class= "fas fa-home"></i>Home
        <% end %>
      </li>
      <li>
        <%= link_to about_path, class:"text-light" do %>
        <i class="fas fa-link"></i>About
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path, class:"text-light" do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class:"text-light" do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
     <% end %>
    </ul>
    </div>
    </div>
    </nav>
    <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
　<% end %>
    </header>

  <main>
  <p id="notice"></p>
  <div class='container'>
   <div class='row'>

    <%= yield %>

   </div>
  </div>
  </main>


  <footer>
    <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
      <p>CopyRight Infratop.inc</p>
    </div>
    </div>
  </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <%= form_with model: @user do |f| %>
 <div>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
 </div>
 <div>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
 </div>
 <div>
  <label for="imputIntroduction">Introduction</label>
  <%= f.text_area :introduction, placeholder:"text" %>
 </div>
 <div>
  <%= f.submit "Update User" %>
 </div>
<% end %>

app/views/users/edit　.html.erb
<h1>Users#edit　</h1>
<p>Find me in app/views/users/edit　.html.erb</p>

app/views/users/index.html.erb
  <div class="col-md-3">
   <%= render 'devise/shared/user_info', user: @user_info %>
   <%= render 'devise/shared/new_book', book: @book %>
  </div>

<div class='col-md-8 offset-md-1'>
<h2>Users</h2><!--user一覧-->
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  </tbody>
  <% end %>
</table>
</div>

app/views/users/show.html.erb
<div class='col-md-3'>
 <%= render 'devise/shared/user_info', user: @user %>
 <%= render 'devise/shared/new_book', book: @book %>
</div>
<div class='col-md-8 offset-md-1'>
<h2>Books</h2>
<table class='table table-hover table-inverse'>
 <thead>
  <tr>
   <th>Title</th>
   <th>Option</th>
   <th colspan="3"></th>
  </tr>
 </thead>
 <tbody>
  <% @books.each do |book| %>
  <tr>
   <td><!--投稿ユーザー画像-->
    <%= link_to image_tag book.user.get_profile_image(100,100) %>
   </td>
   <td>
    <%= link_to book.title, book_path(book) %>
   </td>
   <td>
    <%= book.body %>
   </td>
  </tr>
  <% end %>
 </tbody>
</table>
</div>